services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: getraenke
    network_mode: host
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
